# -*- coding: utf-8 -*-
"""AI LOGIC-coding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kf4o7pvQC1lnRYBaBRx8f6S5Ovhucwqg
"""

'''PART B: Coding Questions

Coding Q1 - Find Peak Element

Problem Statement
A peak element in an array is an element that is strictly greater than its neighbours.
Given a 0-indexed integer array nums, write a function find_peak_element(nums) that returns the index of any one peak element.
You may assume that nums[-1] = nums[n] = -infinity (elements beyond boundaries are negative infinity).
Your solution must run in O(log n) time. If the array contains multiple peaks, returning any one index is acceptable.

Constraints
1 <= nums.length <= 1000
-2^31 <= nums[i] <= 2^31 - 1
nums[i] != nums[i+1] for all valid i

Open Test Cases (Visible to Candidate)
Input:  nums = [1, 2, 3, 1]
Output: 2   (index 2, value 3 is a peak)

Input:  nums = [1, 2, 1, 3, 5, 6, 4]
Output: 5   (index 5, value 6 is a peak; index 1 also valid)'''


def find_peak_element(nums: list[int]) -> int:
    left, right = 0, len(nums) - 1

    # Binary Search loop
    while left < right:
        mid = (left + right) // 2

        # Compare mid element with its right neighbor
        if nums[mid] > nums[mid + 1]:
            # Peak lies on the left side (or is mid itself)
            right = mid
        else:
            # Peak lies strictly on the right side
            left = mid + 1

    # When left == right, we have found a peak element index
    return left

nums = [1, 2, 1, 3, 5, 6, 4]
find_peak_element(nums)

nums = [1, 2, 3, 1]
find_peak_element(nums)

'''Coding Q2 - Group Anagrams

Problem Statement
Given an array of strings strs, group all strings that are anagrams of each other into the same group and return the list of groups.
Two strings are anagrams if they contain the same characters with the same frequencies.
The output groups and strings within each group may be returned in any order.

Constraints
1 <= strs.length <= 10^4
0 <= strs[i].length <= 100
strs[i] consists of lowercase English letters only
Expected time complexity: O(n x k log k) where k is the max string length

Open Test Cases (Visible to Candidate)
Input:  strs = ["eat","tea","tan","ate","nat","bat"]
Output: [["bat"],["nat","tan"],["ate","eat","tea"]]  (any group order)

Input:  strs = [""]
Output: [[""]]'''


from collections import defaultdict

def groupAnagrams(strs: list[str]):
    anagram_map = defaultdict(list)

    for s in strs:
        sorted_key = "".join(sorted(s))


        anagram_map[sorted_key].append(s)

    return list(anagram_map.values())

strs = ["eat","tea","tan","ate","nat","bat"]
groupAnagrams(strs)

strs = [""]
groupAnagrams(strs)

'''Coding Q3 - Kth Largest Element in an Array

Problem Statement
Given an unsorted integer array nums and an integer k, return the k-th largest element in the array.
Note that it is the k-th largest in sorted order, not the k-th distinct element.
You must solve this without fully sorting the array - implement a partition-based (Quickselect) or heap-based approach from scratch.
Do NOT use built-in sort functions as your primary solution.

Constraints
1 <= k <= nums.length <= 10^4
-10^4 <= nums[i] <= 10^4
Expected average time complexity: O(n) (Quickselect) or O(n log k) (heap approach)

Open Test Cases (Visible to Candidate)
Input:  nums = [3, 2, 1, 5, 6, 4],  k = 2
Output: 5

Input:  nums = [3, 2, 3, 1, 2, 4, 5, 5, 6],  k = 4
Output: 4'''



import random

def findKthLargest(nums: list[int], k: int):
    target_index = k - 1

    def partition(left: int, right: int):

        pivot_idx = random.randint(left, right)
        nums[pivot_idx], nums[right] = nums[right], nums[pivot_idx]

        pivot = nums[right]
        i = left

        for j in range(left, right):
            if nums[j] >= pivot:
                nums[i], nums[j] = nums[j], nums[i]
                i += 1

        nums[i], nums[right] = nums[right], nums[i]
        return i

    left, right = 0, len(nums) - 1

    while left <= right:
        pivot_index = partition(left, right)

        if pivot_index == target_index:
            return nums[pivot_index]
        elif pivot_index < target_index:
            left = pivot_index + 1
        else:
            right = pivot_index - 1

    return -1

result = findKthLargest([3, 2, 1, 5, 6, 4], 2)
print("Output:", result)

result = findKthLargest([3, 2, 3, 1, 2, 4, 5, 5, 6],4)

print("Output:", result)

